const addProductToCartConst = {
    ADD_PRODUCT_TO_CART_REQUEST: "ADD_PRODUCT_TO_CART_REQUEST",
    ADD_PRODUCT_TO_CART_SUCCESS: "ADD_PRODUCT_TO_CART_SUCCESS",
    ADD_PRODUCT_TO_CART_FAIL: "ADD_PRODUCT_TO_CART_FAIL",
};

export default addProductToCartConst;
