const forMenuConst = {
    GET_CATEGORY_FOR_MENU_REQUEST: "GET_CATEGORY_FOR_MENU_REQUEST",
    GET_CATEGORY_FOR_MENU_SUCCESS: "GET_CATEGORY_FOR_MENU_SUCCESS",
    GET_CATEGORY_FOR_MENU_FAIL: "GET_CATEGORY_FOR_MENU_FAIL",
};
export default forMenuConst;
