const forSidebarConst = {
    GET_CATEGORY_FOR_SIDEBAR_REQUEST: "GET_CATEGORY_FOR_SIDEBAR_REQUEST",
    GET_CATEGORY_FOR_SIDEBAR_SUCCESS: "GET_CATEGORY_FOR_SIDEBAR_SUCCESS",
    GET_CATEGORY_FOR_SIDEBAR_FAIL: "GET_CATEGORY_FOR_SIDEBAR_FAIL",
};
export default forSidebarConst;
